name: Test (NVC) (dev branch)

# TODO enable other events and/or schedule as required
on:
  workflow_dispatch:
#  push:
#  pull_request:
#  schedule:
#    - cron: '0 15 * * *'

jobs:
  win:
    name: Test (Windows, MSYS2-MinGW64, NVC)
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: dev
          path: OsvvmLibraries
          submodules: recursive
          fetch-depth: 1
      - name: 'Setup MSYS2-MinGW64'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-tcllib
      - name: 'Install NVC'
        run: |
          : # temporary
          wget https://www.nickg.me.uk/files/mingw-w64-x86_64-nvc-1.7.0.r209.g4ef679f1-1-any.pkg.tar.zst
          pacman -U --noconfirm *.zst
          : # TODO install from offical MSYS2 package when available:
          : # pacman -S --noconfirm mingw-w64-x86_64-nvc
      - name: 'Run tests'
        run: tclsh ./OsvvmLibraries/.github/test.tcl NVC
      - name: 'Upload results'
        uses: actions/upload-artifact@v2
        with:
          name: msys2-nvc-MINGW64-log
          path: |
            *.log
            *.yml
            *.html
            *.xml
            reports/*.html
            reports/**/*.html
            logs/**/*.*
          if-no-files-found: error
      - name: 'Check for zero failures'
        run: |
          tests="$(xmllint --xpath 'string(/testsuites/@tests)' .github_OsvvmRegression.xml)"
          failures="$(xmllint --xpath 'string(/testsuites/@failures)' .github_OsvvmRegression.xml)"
          echo "tests: ${tests}  failures: ${failures}"
          if (( $failures != "0" )); then exit 1; fi
