name: OsvvmRegressionOnNVC

# TODO enable other events and/or schedule as required
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  win:
    name: Test (Windows, MSYS2-MinGW64, NVC)
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          path: OsvvmLibraries
          submodules: recursive
      - name: 'Setup MSYS2-MinGW64'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-tcllib

      - name: 'Install NVC'
        run: |
          : # temporary
          wget https://github.com/nickg/nvc/releases/download/r1.13.0/mingw-w64-x86_64-nvc-1.13.0.git20240713.016164d9-1-any.pkg.tar.zst
          pacman -U --noconfirm *.zst
          : # TODO install from offical MSYS2 package when available
          : # pacman -S --noconfirm mingw-w64-x86_64-nvc

      - name: 'Run tests'
        run: tclsh ./OsvvmLibraries/.github/test.tcl NVC

      - name: 'Upload results'
        uses: actions/upload-artifact@v4
        with:
          name: msys2-nvc-MINGW64-log
          path: |
            *.log
            *.yml
            *.html
            *.xml
            reports/*.html
            reports/**/*.html
            logs/**/*.*
            reports/*.css
            reports/osvvm.png
          if-no-files-found: error

      - name: ⏬ Checkout repository
        uses: actions/checkout@v4

      - name: '📥 Download artifact: package'
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: log-*

      - name: 📊 Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          name: OSVVM VC Regression Results
          path: artifacts/**/*.xml
          reporter: java-junit
          list-suites: all
          list-tests: failed