name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:


  lin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - mcode
          - llvm
#          - gcc
    name: '🐧 Ubuntu · ${{ matrix.backend }}'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        path: OsvvmLibraries
        submodules: recursive

    - name: '⚙️ Setup GHDL'
      uses: ghdl/setup-ghdl-ci@master
      with:
        backend: ${{ matrix.backend }}

    - name: '🛠️ Install tcl'
      run: |
        sudo apt update -qq
        sudo apt install -y tcl tcllib

    - name: '🚧 Run tests'
      run: tclsh ./OsvvmLibraries/.github/test.tcl

    - name: 'Collect Artifacts'
      run: mv logs/*/OsvvmLibraries_RunAllTests_ghdl.log OsvvmLibraries_RunAllTests_ghdl.log
      
    - name: '📤 Upload artifact: logs'
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-ghdl-${{ matrix.backend }}-log
        path: |
          OsvvmLibraries_RunAllTests_ghdl.log
          OsvvmLibraries_RunAllTests_ghdl.yml
        if-no-files-found: error


  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          #- {icon: '🟪', msys: 'MINGW32', arch: i686,        pkg: "llvm" } ! Not yet functional
          - {icon: '🟦', msys: 'MINGW64', arch: x86_64,      pkg: 'llvm' }
          - {icon: '🟨', msys: 'UCRT64',  arch: ucrt-x86_64, pkg: 'llvm' } #! Experimental
          - {icon: '🟪', msys: 'MINGW32', arch: i686,        pkg: 'mcode' }
          #- {icon: '🟦', msys: 'MINGW64', arch: x86_64,      pkg: "mcode" } ! Simulation with mcode is not yet supported on win64
          #- {icon: '🟨', msys: 'UCRT64',  arch: x86_64,      pkg: "mcode" } ! Experimental; Simulation with mcode is not yet supported on win64
    name: '${{ matrix.icon }} ${{ matrix.msys }} · ${{ matrix.pkg }}'
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msys }}
        update: true
        install: >
          git
          mingw-w64-${{ matrix.arch }}-tcl
          mingw-w64-${{ matrix.arch }}-tcllib

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        path: OsvvmLibraries
        submodules: recursive

    - name: '⚙️ Setup GHDL'
      uses: ghdl/setup-ghdl-ci@master
      with:
        backend: ${{ matrix.pkg }}

    - name: '🚧 Run tests'
      run: tclsh ./OsvvmLibraries/.github/test.tcl

    - name: 'Collect Artifacts'
      run: mv logs/*/OsvvmLibraries_RunAllTests_ghdl.log OsvvmLibraries_RunAllTests_ghdl.log
      
    - name: '📤 Upload artifact: logs'
      uses: actions/upload-artifact@v2
      with:
        name: msys2-ghdl-${{ matrix.pkg }}-${{ matrix.msys }}-log
        path: |
          OsvvmLibraries_RunAllTests_ghdl.log
          OsvvmLibraries_RunAllTests_ghdl.yml
        if-no-files-found: error
